#!/usr/bin/env bash
#
# Runs performance tests
#

cd "perf-tests" || exit 1
. ../mo
. functions.sh

# Declare variables for the templates
restsh.util.setvars config >/dev/null
restsh.util.setvar LARGE.array >/dev/null

echo "--"
echo "Test large arrays"
time mo template.json | jq "." >/dev/null

echo "--"
echo "Test large template"
time mo template2.json | jq "." >/dev/null
